# Pandas
-Data analysis library/ Work on data secienece 
2 inspector
    -Series--Single Dimention 
    -Data Frame-- Multidimention
   Note: create labels for us which array cant

In [2]:
import pandas as pd

# Series
  -Series are one dimention 
  -its can be concantenate vertically not horizontally

In [3]:
s1=pd.Series([1,2,3,4])

In [4]:
type(s1)

pandas.core.series.Series

In [5]:
print(s1)

0    1
1    2
2    3
3    4
dtype: int64


In [6]:
s1.values

array([1, 2, 3, 4], dtype=int64)

In [7]:
s1.index=["one","two","three","four"] #indexes can be our choice
s1

one      1
two      2
three    3
four     4
dtype: int64

In [8]:
s1["one"]

1

In [9]:
s1[0]

1

In [12]:
s2= pd.Series([1,2,3,4,5],index=["apples","bananas", "oranges", "peers","two"])
s2

apples     1
bananas    2
oranges    3
peers      4
two        5
dtype: int64

In [15]:
s2["apples"]

1

In [16]:
s1+s2# will not add/merge until series is not same

apples     NaN
bananas    NaN
four       NaN
one        NaN
oranges    NaN
peers      NaN
three      NaN
two        7.0
dtype: float64

In [17]:
s1*s2

apples      NaN
bananas     NaN
four        NaN
one         NaN
oranges     NaN
peers       NaN
three       NaN
two        10.0
dtype: float64

In [18]:
s1-s2

apples     NaN
bananas    NaN
four       NaN
one        NaN
oranges    NaN
peers      NaN
three      NaN
two       -3.0
dtype: float64

In [19]:
s1/s2

apples     NaN
bananas    NaN
four       NaN
one        NaN
oranges    NaN
peers      NaN
three      NaN
two        0.4
dtype: float64

In [20]:
s1&s2

apples     False
bananas    False
four       False
one        False
oranges    False
peers      False
three      False
two        False
dtype: bool

In [21]:
s3 =pd.Series(range(10))
s3

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [26]:
s4=pd.Series(range(10,21))
s4

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64

In [28]:
s4.shape

(11,)

In [29]:
s3+s4

0     10.0
1     12.0
2     14.0
3     16.0
4     18.0
5     20.0
6     22.0
7     24.0
8     26.0
9     28.0
10     NaN
dtype: float64

In [30]:
import numpy as np
arr1=np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [35]:
arr2=np.arange(6)
arr2

array([0, 1, 2, 3, 4, 5])

In [21]:
#arr1+arr2 will not be merged until the values are same

In [22]:
s2

apples     1
bananas    2
oranges    3
peers      4
two        5
dtype: int64

In [23]:
s2[1:3] #slicing

bananas    2
oranges    3
dtype: int64

In [24]:
s2["apples":"peers"]

apples     1
bananas    2
oranges    3
peers      4
dtype: int64

In [25]:
s2[2:4]=23
s2

apples      1
bananas     2
oranges    23
peers      23
two         5
dtype: int64

# Lambda functions are anonymous functions 

In [26]:
new=pd.Series([99,100,8,89], index=["sadaf","ali","saad","waji"])
new

sadaf     99
ali      100
saad       8
waji      89
dtype: int64

In [27]:
#apply function
def myfuc(marks):
    return marks/100

In [28]:
new.apply(myfuc)

sadaf    0.99
ali      1.00
saad     0.08
waji     0.89
dtype: float64

In [29]:
#apply lambda function
new.apply(lambda x:x/100)

sadaf    0.99
ali      1.00
saad     0.08
waji     0.89
dtype: float64

In [30]:
new.apply(lambda x:np.where(x>50, "Pass", "fail")) #one time function , cant be called by anyone

sadaf    Pass
ali      Pass
saad     fail
waji     Pass
dtype: object

In [31]:
new.apply(lambda x:np.where(x>50, "Pass", "fail"))

sadaf    Pass
ali      Pass
saad     fail
waji     Pass
dtype: object

In [32]:
new[['sadaf','waji']]

sadaf    99
waji     89
dtype: int64

In [33]:
new.value_counts()

99     1
100    1
8      1
89     1
dtype: int64

In [34]:
s5= pd.Series(100, index=s2.index)
s5


apples     100
bananas    100
oranges    100
peers      100
two        100
dtype: int64

In [35]:
new[['sadaf','waji']]

sadaf    99
waji     89
dtype: int64

In [36]:
np.linspace(1,10,10) #linear space series generater function

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
s6=pd.Series({'a':1,'b':2,'c':3,'d':4,})
s6
s6.shape
s6.size
s6.count()#dont count NAN

4

In [38]:
s1

one      1
two      2
three    3
four     4
dtype: int64

In [39]:
s1.value_counts()

1    1
2    1
3    1
4    1
dtype: int64

# Peeking at data with heads, tails, and take
-By default, these return the first or last five rows,


In [40]:
s1.head()

one      1
two      2
three    3
four     4
dtype: int64

In [41]:
s7=pd.Series([1,2,3,np.nan,]) #generate nan 
s7

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [42]:
np.random.seed(123456) #seed fix the number
s1=pd.Series(np.random.randn(3))
s2=pd.Series(np.random.randn(3))

In [43]:
combined=pd.concat([s1,s2])
combined

0    0.469112
1   -0.282863
2   -1.509059
0   -1.135632
1    1.212112
2   -0.173215
dtype: float64

In [44]:
combined[0]#gives 2 0 gives 2 ones

0    0.469112
0   -1.135632
dtype: float64

In [45]:
combined.reindex()

0    0.469112
1   -0.282863
2   -1.509059
0   -1.135632
1    1.212112
2   -0.173215
dtype: float64

In [46]:
#re index
combined.reset_index(drop=True) #will drop purana index will set new index

0    0.469112
1   -0.282863
2   -1.509059
3   -1.135632
4    1.212112
5   -0.173215
dtype: float64

In [47]:
combined[4]= 40
combined

0     0.469112
1    -0.282863
2    -1.509059
0    -1.135632
1     1.212112
2    -0.173215
4    40.000000
dtype: float64

In [48]:
combined

0     0.469112
1    -0.282863
2    -1.509059
0    -1.135632
1     1.212112
2    -0.173215
4    40.000000
dtype: float64

In [50]:
combined.reset_index(drop=True, inplace=True)
combined

0     0.469112
1    -0.282863
2    -1.509059
3    -1.135632
4     1.212112
5    -0.173215
6    40.000000
dtype: float64

In [51]:
combined[5]=50
combined

0     0.469112
1    -0.282863
2    -1.509059
3    -1.135632
4     1.212112
5    50.000000
6    40.000000
dtype: float64

In [57]:
del combined[6]
combined

0     0.469112
1    -0.282863
2    -1.509059
3    -1.135632
5    50.000000
dtype: float64

In [60]:
combined

0     0.469112
1    -0.282863
2    -1.509059
3    -1.135632
5    50.000000
dtype: float64

In [64]:
combined[1:3]

1   -0.282863
2   -1.509059
dtype: float64

In [68]:
#del combined[[1,2] it doesnt work

In [70]:
combined

0     0.469112
1    -0.282863
2    -1.509059
3    -1.135632
5    50.000000
dtype: float64

In [72]:
combined.copy()

0     0.469112
1    -0.282863
2    -1.509059
3    -1.135632
5    50.000000
dtype: float64

In [76]:
newCom= combined.copy()# this copy is not by reference it is by value
newCom

0     0.469112
1    -0.282863
2    -1.509059
3    -1.135632
5    50.000000
dtype: float64

In [82]:
oldCom = newCom # this copy is by reference 
combined

0     0.469112
1    -0.282863
2    -1.509059
3    -1.135632
5    50.000000
dtype: float64

# Panda Data Frame
-Structure of Pandas
-We can pass dic 

In [85]:
students={'roll':[1,2,3,4,5],
          'name':['ali', 'sadaf','rayyan','rustam','raju'],
          'course':['AIC','Python','Pandas','Numpy','Mata'],
          'mode':['online','offline','onsite','offline','onsite']}
students

{'roll': [1, 2, 3, 4, 5],
 'name': ['ali', 'sadaf', 'rayyan', 'rustam', 'raju'],
 'course': ['AIC', 'Python', 'Pandas', 'Numpy', 'Mata'],
 'mode': ['online', 'offline', 'onsite', 'offline', 'onsite']}

In [90]:
df=pd.DataFrame(students) #for creating DF we need all values to be same
df

roll    name  course     mode
0     1     ali     AIC   online
1     2   sadaf  Python  offline
2     3  rayyan  Pandas   onsite
3     4  rustam   Numpy  offline
4     5    raju    Mata   onsite