In [5]:
import numpy as np

In [6]:
x= np.array([1,2,3,4])
x.shape

(4,)

In [8]:
# Dimensions 
x.ndim

1

In [10]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
arr1d= np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
import numpy as np
arr2d = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222, 3333]])

In [14]:
arr2d.shape

(4, 3)

In [18]:
#                             1 R 20 Col
arr2d = np.arange(20).reshape(1,20)
print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
(1, 20)
2


In [21]:
#                             20 rows 1 Col   
arr2d = np.arange(20).reshape(20,1)
print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]
(20, 1)
2


In [24]:
#                            4Rows 5Col
arr2d = np.arange(20).reshape(4,5)
print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
2


In [26]:
arr2d.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
#converting flaten array (1d array) we have 2 function ravel or flatten 
arr2d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
# Scalar
arr= np.array(10)
arr

array(10)

In [36]:
arr.ndim

0

In [4]:
food=['ham','egg','fish']
for snack in food:
    print(snack)
    


ham
egg
fish


In [23]:
m = np.array([np.arange(2),np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [26]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [29]:
#np.array?

In [39]:
a= np.array([[1,2,3,],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [44]:
a.dtype.itemsize

4

In [48]:
b=np.arange(7, dtype='f')
b


array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)