In [3]:
import numpy as np

In [11]:
def numpysum(n):
 a = numpy.arange(n) ** 2
 b = numpy.arange(n) ** 3
 c = a + b
 return c

In [14]:
numpysum

<function __main__.numpysum(n)>

In [7]:
a=1
b=2
a,b=b,a
a
b

1

In [17]:
print('hello')

hello


In [31]:
if 43 < 0:
    print('negative')
else: 
    print('positive')

positive


In [33]:
#Loop
food=['ham','orange','mango']
for snack in food:
    print (snack)

ham
orange
mango


In [38]:
#step of two loop
for i in range(1,9,2):
    print(i)

1
3
5
7


In [42]:
#break a loop after a number
for i in range(9):
    print(i)
    if i ==3:
        print('three')
        break

0
1
2
3
three


In [49]:
#Print the numbers 0-4,skipping 3 as follows:

for i in range(5):
    if i == 3:
        print('Three')
        continue
    print(i)

0
1
2
Three
4


In [50]:
#Add an else clause as follows:
for i in range(10):
    print(i)
else:
    print(i,'in else clause')

0
1
2
3
4
5
6
7
8
9
9 in else clause


In [12]:
import math

In [11]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

math.pow(2,3)

In [18]:
from math import pow
pow(2,3)

8.0

In [30]:
import numpy as np
import matplotlib.pyplot as plt

In [31]:
#numpy arrays

In [52]:
#Adding vectors using pure Python with out numpy 
def pythonsum(n):
    a= range(n)
    b=range(n)
    c=[]
    for i in range(len(a)):
        a[i]=i**2
        b[i]=i**3
        c.append(a[i]+b[i])
    return c

In [1]:
import numpy as np

In [6]:
my_arr=np.arange(1000000)
my_list = list(range(1000000))

In [13]:
#Now let’s multiply each sequence by 2:
for _ in range(10): my_arr2 = my_arr * 2
print(my_arr2)

[      0       2       4 ... 1999994 1999996 1999998]


In [19]:
for _ in range(10): my_list2 = [x * 2 for x in my_list]

In [23]:
# Generate some random data
data=np.random.randn(2,3)
data

array([[-0.17901079,  1.03398494,  0.03092994],
       [-0.01307032,  0.36124621,  1.38388003]])

In [25]:
data*10

array([[-1.79010788, 10.33984939,  0.30929942],
       [-0.13070323,  3.61246211, 13.83880032]])