Problem  1

Convert a 1D array to a 2D array with 2 rows

Input:
```
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```



In [1]:
import numpy as np

In [2]:
arr2d=np.arange(10).reshape(2,5)
print(arr2d)
type(arr2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


numpy.ndarray

Problem  2

Extract all odd numbers from arr

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```



In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr=arr[arr % 2 == 1]
print(arr)

[1 3 5 7 9]


Problem  3

Replace all odd numbers in arr with -1

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```



In [4]:
np.where(arr%2!=0, -1,arr)

array([-1, -1, -1, -1, -1])

Problem  4

Replace all odd numbers in arr with -1 without changing arr

Input:

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

Desired Output:

```
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```




In [5]:
odd_num=np.where(arr%2!=0, -1,arr)
print(odd_num)
print(arr)

[-1 -1 -1 -1 -1]
[1 3 5 7 9]


Problem  5

Stack arrays a and b vertically

Input



```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:


```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```




In [6]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Problem  6

Stack the arrays a and b horizontally.

Input


```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:



```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```




In [7]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Problem  7

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:



```
a = np.array([1,2,3])
```


Desired Output:



```
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```




In [8]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Problem  8

From array a remove all items present in array b

Input:


```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

Desired Output:

```
array([1,2,3,4])
```




In [9]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

Problem  9

Get the positions where elements of a and b match

Input:



```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```


Desired Output:



```
(array([1, 3, 5, 7]),)
```



In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

Problem  10

Swap columns 1 and 2 in the array arr.

```
arr = np.arange(9).reshape(3,3)
```

Output:



```
array([[1, 0, 2],
      [4, 3, 5],
      [7, 6, 8]])
```




In [11]:
arr=np.arange(9).reshape(3,3)
arr[:, [1,0,2]]
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr[:, [1,0,2]]
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Problem  11

From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

Input:


```
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```


In [13]:
#Using np.where
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


Problem  12

Compute the counts of unique values row-wise.

Input:



```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```



Desired Output:



```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```



In [14]:
# Solution
def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

# Print
counts_of_all_values_rowwise(arr)

[[1, 1, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 1]]

Problem  13

Compute the one-hot encodings (dummy binary variables for each unique value in the array)

In [75]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

array([2, 3, 2, 2, 2, 1])

Problem  14

Create the ranks for the given numeric array a.

Input:



```
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
#> [ 9  4 15  0 17 16 17  8  9  0]
```

Desired output:

```
[4 2 6 0 8 7 9 3 5 1]
```

In [73]:
import numpy as np
from scipy.stats import rankdata

np.random.seed(10)
a = np.random.randint(20, size=10)

ranks = rankdata(a)

print(ranks - 1) # subtract 1 to get 0-based indexing

[4.5 2.  6.  0.5 8.5 7.  8.5 3.  4.5 0.5]


Problem  15

Create a rank array of the same shape as a given numeric array a.

Input:



```
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
#> [[ 9  4 15  0 17]
#>  [16 17  8  9  0]]
```


Desired output:



```
#> [[4 2 6 0 8]
#>  [7 9 3 5 1]]
```



In [69]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
print('ans')
print(a.ravel().argsort().argsort().reshape(a.shape))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
ans
[[4 2 6 0 8]
 [7 9 3 5 1]]


In [71]:
import numpy as np
from scipy.stats import rankdata

np.random.seed(10)
a = np.random.randint(20, size=[2,5])

ranks = np.apply_along_axis(rankdata, 1, a) - 1
print(ranks.astype(int))

[[2 1 3 0 4]
 [3 4 1 2 0]]


Problem  16

Compute the min-by-max for each row for given 2d numpy array

Input:

```
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
#> array([[9, 9, 4],
#>        [8, 8, 1],
#>        [5, 3, 6],
#>        [3, 3, 3],
#>        [2, 1, 9]])
```

Desired Output:

```
array([ 0.44444444,  0.125     ,  0.5       ,  1.        ,  0.11111111])
```

In [76]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
np.apply_along_axis(lambda x:np.min(x)/np.max(x), arr=a, axis=1)

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

Problem  17

Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False

Input
```
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#> Array: [0 0 3 0 2 4 2 2 2 2]
```
Desired Output:
```
#> [False  True False  True False False  True  True  True  True]
```

In [83]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
out=np.full(a.shape[0],True)
out

Array:  [0 0 3 0 2 4 2 2 2 2]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [87]:
out[unique_positions] = False

print(out)

[False  True False  True False False  True  True  True  True]


Problem  18

Drop all nan values from a 1D numpy array

Input:
```
np.array([1,2,3,np.nan,5,6,7,np.nan])
```
Desired Output:
```
array([ 1.,  2.,  3.,  5.,  6.,  7.])
```

Problem 19

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```

Problem 20

Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.


Input
```
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1]

```
Desired Output:
```
#> [[2 2 2]
#>  [2 2 2]
#>  [2 2 2]]
```

Problem 21

Find the index of 5th repetition of number 1 in x.

Input:

```
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
```



Problem 22

Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

Problem 23

 From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

Input:
```
arr = np.arange(15) 
arr
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

Desired Output:
```
#> [[ 0  1  2  3]
#>  [ 2  3  4  5]
#>  [ 4  5  6  7]
#>  [ 6  7  8  9]
#>  [ 8  9 10 11]
#>  [10 11 12 13]]
```

In [9]:
import numpy as np
#Create a 3×3 numpy array of all True’s
np.full((3, 3), True, dtype=bool)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
# Alternate method:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [28]:
# How to extract items that satisfy a given condition from 1D array?
#Extract all odd numbers from arr
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1=arr[arr % 2 == 1]
print('odd numbers', arr1)

odd numbers [1 3 5 7 9]


In [36]:
#How to replace items that satisfy a condition with another value in numpy array?
# Replace all odd numbers in arr with -1
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr
arr[arr % 2==1]= -4
arr

array([ 0, -4,  2, -4,  4, -4,  6, -4,  8, -4])

In [45]:
#6. How to replace items that satisfy a condition without affecting the original array?
#Replace all odd numbers in arr with -1 without changing arr
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out=np.where(arr% 2==1,'odd', arr)
out

array(['0', 'odd', '2', 'odd', '4', 'odd', '6', 'odd', '8', 'odd'],
      dtype='<U11')

In [47]:
out=np.where(arr% 2==1,-1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [54]:
# Convert a 1D array to a 2D array with 2 rows
arr=np.arange(10)
arr2d=arr.reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
#How to stack two arrays vertically?
# Stack arrays a and b vertically
a=np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# Method 1:concatenate
np.concatenate([a, b], axis=0)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [74]:
#Method 2
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [70]:
dir(np) #functions of numpy 

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [78]:
#method 3
a=np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.r_[a,b] #_r Translates slice objects to concatenation along the first axis.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [81]:
a.size

10

In [83]:
b.size

10

In [85]:
a.shape

(2, 5)

In [87]:
b.shape

(2, 5)

In [88]:
a.ndim

2

In [89]:
b.ndim

2

In [86]:
#How to stack two arrays horizontally?
#Stack the arrays a and b horizontally.
a=np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
arr=np.vstack(a,b)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given