In [1]:
import numpy as np

In [2]:
x= np.array([1,2,3,4])

In [3]:
# 1d = Vector
# 2d = Matrix
# 3d = Cube
#  .
#  .
# nd =  ...
x.shape

(4,)

In [4]:
# Dimentions
x.ndim

1

In [5]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2d = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222, 3333]])

In [8]:
arr2d.shape

(4, 3)

In [9]:
arr2d = np.arange(20).reshape(1,20)
print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
(1, 20)
2


In [10]:
arr2d = np.arange(20).reshape(20,1)
print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]
(20, 1)
2


In [11]:
arr2d = np.arange(20).reshape(4,5)
print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
2


In [12]:

arr2d.reshape(20)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
#converting flaten array (1d array) we have 2 function ravel or flatten 
arr2d.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
# Scaler 
arr = np.array(10)
arr

array(10)

In [17]:
arr.ndim

0

In [18]:
# 1d = vector 
arr = np.array([10])
arr

array([10])

In [19]:
# 2d = matrix 
arr =  np.array([[10]])
arr

array([[10]])

In [20]:
# 3d array 
arr3d = np.arange(64).reshape(4,4,4) # (depth,row,colums) rubic cube is example of 3d array 
                                     # (matrix, row ,col)
                                     # depth row columns are of same matrix can be different depends on view angle
print(arr3d)
print(arr3d.shape)
print(arr3d.ndim)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
(4, 4, 4)
3


In [21]:
arr3d[2,1,3]

39

In [22]:
arr3d[2][1][3]

39

In [23]:
# In python for multiply an array (vectorize operation ) every dimension value is effected
z= []
x = arr3d[0][1]
print(x)
for a in x:
    z.append(a*2)
z

[4 5 6 7]


[8, 10, 12, 14]

In [24]:
arr3d[2][1][3]= arr3d[2][1][3]*10
arr3d

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38, 390],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]]])

In [25]:
y = np.arange(4)

In [26]:
y

array([0, 1, 2, 3])

In [27]:
x+y

array([ 4,  6,  8, 10])

In [28]:
x*2

array([ 8, 10, 12, 14])

In [29]:
#miirroring = elementwise operation
a= np.arange(25).reshape(5,5)
b= np.arange(25,50).reshape(5,5)

In [30]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [74]:
#mirror or element wise (unlike linear algebra. it is only multiplying crossponding entities)
a * b # multiply

array([[   0,   26,   54,   84,  116],
       [ 150,  186,  224,  264,  306],
       [ 350,  396,  444,  494,  546],
       [ 600,  656,  714,  774,  836],
       [ 900,  966, 1034, 1104, 1176]])

In [73]:
#mirror or element wise
a + b # addition

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [75]:
#multiplication like linear algebra (rows of first matrix must be equal to columns of seconds matrix)
a@b # matrix multiplication 

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

# Array Slicing and Indexing

In [76]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
type(a)

numpy.ndarray

In [78]:
type(a[2,3])

numpy.int32

In [79]:
a[2,3] # it is indexing  and it will result only value

13

In [82]:
# array [row,col]
#       [strat:end , start: end]
a[2:3,3:4] # it is slicing and it is array with same dimension as orignal array have

array([[13]])

In [84]:
a[1:4,3]

array([ 8, 13, 18])

In [85]:
a[4:, 4:]

array([[24]])

# Querrying Array

In [86]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
a>5 # mask

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [89]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [90]:
mask=a>5 #mask
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [100]:
a[a>7]=0
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [111]:
a= np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
np.where(a>7,0,a) # it this dimension is not changing

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [115]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [114]:
a[(a%2==0) | (a%7==0)]

array([ 0,  2,  4,  6,  7,  8, 10, 12, 14, 16, 18, 20, 21, 22, 24])

In [116]:
np.where((a%2==0) | (a%7==0),"Wow","Oh")

array([['Wow', 'Oh', 'Wow', 'Oh', 'Wow'],
       ['Oh', 'Wow', 'Wow', 'Wow', 'Oh'],
       ['Wow', 'Oh', 'Wow', 'Oh', 'Wow'],
       ['Oh', 'Wow', 'Oh', 'Wow', 'Oh'],
       ['Wow', 'Wow', 'Wow', 'Oh', 'Wow']], dtype='<U3')


# Combining Arrays

In [ ]:
#stacking

In [119]:
a= np.arange(25).reshape(5,5)

In [122]:
print(a)
b.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


(5, 5)

In [121]:
b= np.arange(25).reshape(5,5)

In [124]:
print(b)
b.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


(5, 5)

In [125]:
np.concatenate((a,b))  # default axis is 0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [128]:
np.concatenate((a,b),axis=1)  # 1 will increase columns

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 20, 21, 22, 23, 24]])

In [129]:
np.concatenate((a,b),axis=0) # 0 will increase rows

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [130]:
np.stack((a,b)) 

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [131]:
np.hstack((a,b))  # equal to concatenate with axis= 1

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 20, 21, 22, 23, 24]])

In [132]:
np.vstack((a,b))  # equal to concatenate with axis= 0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [134]:
newA = np.arange(5).reshape(5)
newA

array([0, 1, 2, 3, 4])

In [138]:
newB = np.arange(5,10).reshape(5)
newB

array([5, 6, 7, 8, 9])

In [139]:
np.stack((newA,newB))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Many other functions (Read recommend book )